version: '3'
services:
  jupyter:
    build: .
    volumes:
     - ${LOCAL_WORKING_DIR}:/data/jupyter
     - ${LOCAL_DATASETS}:/data/jupyter/datasets
     - ${LOCAL_MODULES}:/git/python_modules
     - ${LOCAL_SSL_CERTS}:/opt/ssl-certs/jupyter
    ports:
     - "${PORT}:8888"
    container_name: keras_jupyter
    command: "start-notebook.sh \
        --NotebookApp.password=${ACCESS_TOKEN} \
        --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]